namespace: default

env:
  HTTP_ADDR: :3000

image:
  name: ghcr.io/bnussman/beep
  tag: main
  pull: Always

deployment:
  timestamp: 2006-01-02T15:04:05
  replicas: 3
  container:
    name: api
    port: 3000

service:
  type: LoadBalancer
  port: 443
