name: staging
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 🔑 Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 💾 Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile
          tags: bnussman/api:staging
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.ridebeep.app
    steps:
      - name: 📃 Import kube config
        run: |
          mkdir -p $HOME/.kube/
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      - name: 📦 Install helm
        run: |
          curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
          mv linux-amd64/helm /usr/local/bin/helm
          helm version
      - uses: actions/checkout@v4
      - name: 🔍 Lint helm charts
        run: helm lint ./.github/helm/ -f ./.github/helm/values-staging.yaml
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: 🔐 Inject Secrets
        run: bun run .github/helm/inject.js
        env:
          secrets: ${{ toJSON(secrets) }}
      - run: cat .github/helm/templates/configmap.yaml
      - name: 🚀 Deploy api
        run: |
          helm upgrade --install --atomic --timeout 5m api ./.github/helm/ -f ./.github/helm/values-staging.yaml --namespace beep --create-namespace